name = "Lividjava's Create"
author = "LividJava"
version = "0.4.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5f44a253c701a771da1649ba0f32da9416ac275b77bb50613c700fd5671e6dd"

[versions]
forge = "43.2.4"
minecraft = "1.19.2"
