name = "LividJava's Create"
author = "LividJava"
version = "0.5.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f8465926f92bc036032f904acfe01d20410f2fd9c32cba5fcd53256cf04cc0b"

[versions]
forge = "43.2.4"
minecraft = "1.19.2"
