name = "LividJava's Create"
author = "LividJava"
version = "0.5.0a-hotfix2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80274666ea6aee8e1bc270972ee215b105ab1504ee34bcaea5299be97ab587da"

[versions]
forge = "43.2.4"
minecraft = "1.19.2"
