name = "Lividjava's Create"
author = "LividJava"
version = "0.4.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a864cb6d1952ca146dadd5f98e4bd09a626c7c316d774d35cb1a24ab3b31a86d"

[versions]
forge = "43.2.4"
minecraft = "1.19.2"
