name = "LividJava's Create"
author = "LividJava"
version = "0.4.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "223283cc85eaa2cdec818a8c5f4ce727e709c44fa5e347fcf511eab6cfb8a3c3"

[versions]
forge = "43.2.4"
minecraft = "1.19.2"
