name = "Lividjava's Create"
author = "LividJava"
version = "0.4.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15fbeffeabe4133c430616f6240a826c3d8d81ed38cd17e6a032ce937d2892ae"

[versions]
forge = "43.2.4"
minecraft = "1.19.2"
