name = "LividJava's Create"
author = "LividJava"
version = "0.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c5b7d62a84a16048c93e64ace8f41649efb2d66ce591304e99f0633a57bcd94"

[versions]
forge = "43.2.4"
minecraft = "1.19.2"
