name = "LividJava's Create"
author = "LividJava"
version = "0.5.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dcddc5c2ad69c6391281f39eeddc4e4129dfc1be08bab18f993c83c2df3f1e6"

[versions]
forge = "43.2.4"
minecraft = "1.19.2"
